#!/bin/bash

# This is a thin wrapper around roicoin-cli that strips the Windows-style EOLs
# from the output if present. It is necessary when using roicoin-cli.exe on
# Linux since shells will interpret the line-endings as part of the result.

CURDIR=$(cd $(dirname "$0"); pwd)
# Get BUILDDIR and REAL_ROICOIND

# Grab the value of $REAL_ROICOINCLI which may be roicoin-cli.exe.
. "${CURDIR}/tests-config.sh"

"${REAL_ROICOINCLI}" "$@" | sed 's/\r//'
